name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake
  - intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - pip:
    - graphviz
